# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list

  init-git-repo:
    cmds:
      - git init
    status:
      - test -d .git
    internal: true

  create-env-file:
    cmds:
      - cp .env.example .env
    status:
      - test -f .env
    internal: true

  create-data-dir:
    cmds:
      - mkdir -p data
    status:
      - test -d data
    internal: true

  install-pre-commit:
    cmds:
      - uv tool install pre-commit
      - uv tool run pre-commit install
    status:
      - test -f .git/hooks/pre-commit
    internal: true

  setup:
    cmds:
      - task: init-git-repo
      - task: create-env-file
      - task: create-data-dir
      - task: install-pre-commit
      - uv sync --all-groups --all-extras
    desc: Setup development environment

  lint:
    cmds:
      - uv tool run pre-commit run --all-files
    desc: Run linters

  test:
    cmds:
      - uv run pytest
    desc: Run tests

  bump-version:
    cmds:
      - uv version --bump {{.BUMP}}
    requires:
      vars:
        - name: BUMP
          enum: [patch, minor, major]
    desc: Bump project version

  create-git-tag:
    cmds:
      - git tag v$(uv version --short)
      - git push --tags
    desc: Create and push a git tag for the current version

  run:
    cmds:
      - uv run src/poor_mans_ui/main.py
    desc: Run the app
